# Generated by Django 4.2.8 on 2024-01-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CairoCoinPlus', '0004_apiuser_history_day_apiuser_history_alltime_apilimit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilimit',
            name='last_used',
            field=models.DateTimeField(default='0'),
        ),
        migrations.AlterField(
            model_name='apiuser_history_alltime',
            name='token_used',
            field=models.IntegerField(default=0),
        ),
    ]
