# Generated by Django 4.2.8 on 2024-01-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CairoCoinPlus', '0005_alter_apilimit_last_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilimit',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
