# Generated by Django 4.2.8 on 2024-02-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CairoCoinPlus', '0006_alter_apilimit_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='name',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
