# Generated by Django 4.2.8 on 2024-02-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CairoCoinPlus', '0007_apikey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
