# Generated by Django 4.2.8 on 2024-02-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CairoCoinPlus', '0008_alter_apikey_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='token_limit',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='token_used',
            field=models.IntegerField(default=0),
        ),
    ]
