# Generated by Django 4.2.8 on 2024-02-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CairoCoinPlus', '0009_alter_apikey_name_alter_apikey_token_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apiuser_history_day',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
