# Generated by Django 4.2.8 on 2024-02-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CairoCoinPlus', '0011_alter_apikey_user_alter_apiuser_history_day_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(default=''),
        ),
    ]
