# Generated by Django 4.2.8 on 2024-02-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CairoCoinPlus', '0012_alter_apikey_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser_history_day',
            name='token_limit',
            field=models.IntegerField(default=100),
        ),
    ]
