# Generated by Django 4.2.8 on 2024-01-28 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CairoCoin', '0004_alter_bankrate_bhd_alter_bankrate_gbp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='xPlus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('rate_bi', models.FloatField()),
                ('index_bi', models.FloatField()),
                ('rate_bm', models.FloatField()),
                ('index_bm', models.FloatField()),
                ('rate_g', models.FloatField()),
                ('index_g', models.FloatField()),
            ],
        ),
    ]
