# Generated by Django 4.2.8 on 2024-02-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CairoCoin', '0006_gold_era_gold_era_ingot_gold_lpg_gold_lpg_ingot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xplus',
            name='index_b',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='xplus',
            name='rate_b',
            field=models.FloatField(default=0),
        ),
    ]
